guest_list = ['lena', 'vera', 'jasper']
print(f'Liebe {guest_list[0].title()}, hiermit lade ich dich zum Spekulatiusessen ein.')
print(f'Lieber {guest_list[2].title()}, hiermit lade ich dich zum Spekulatiusessen ein.')
print(guest_list[2].title())
guest_list[2] = 'eric'
print(guest_list)
print(f'Liebe {guest_list[0].title()}, hiermit lade ich dich zum Spekulatiusessen ein.')
print(f'Lieber {guest_list[2].title()}, hiermit lade ich dich zum Spekulatiusessen ein.')
guest_list.append('theresa')
guest_list.insert(0, 'nadine')
guest_list.insert(3, 'lisa')
print(guest_list)
print(f'Liebe {guest_list[0].title()}, hiermit lade ich dich zum Spekulatiusessen ein.')
print(f'Liebe {guest_list[1].title()}, hiermit lade ich dich zum Spekulatiusessen ein.')
print(f'Liebe {guest_list[2].title()}, hiermit lade ich dich zum Spekulatiusessen ein.')
print(f'Liebe {guest_list[3].title()}, hiermit lade ich dich zum Spekulatiusessen ein.')
print(f'Lieber {guest_list[4].title()}, hiermit lade ich dich zum Spekulatiusessen ein.')
print(f'Liebe {guest_list[5].title()}, hiermit lade ich dich zum Spekulatiusessen ein.')
message2 = 'Leider kann ich nur zwei Personen zum Spekulatiusessen einladen'
print(message2)
shrinking_guestlist = guest_list.pop(5)
print(shrinking_guestlist)
print(f'Liebe {shrinking_guestlist.title()}, leider kann ich dich nicht einladen.')
shrinking_guestlist2 = guest_list.pop(4)
print(f'Lieber {shrinking_guestlist2.title()}, leider kann ich dich nicht einladen.')
shrinking_guestlist3 = guest_list.pop(3)
print(f'Liebe {shrinking_guestlist3.title()}, leider kann ich dich nicht einladen.')
shrinking_guestlist4 = guest_list.pop(2)
print(f'Liebe {shrinking_guestlist4.title()}, leider kann ich dich nicht einladen.')
print(f'Liebe {guest_list[1].title()}, hiermit lade ich dich doch noch ein')
print(f'Liebe {guest_list[0].title()}, hiermit lade ich dich doch noch ein.')
del guest_list[1]
print(guest_list)
del guest_list[0]
print(guest_list)
print(len(guest_list))
